### ISSUE TITLE
Missing search results in 0.8.4

### ISSUE THREAD

**Issue by GediminasMasaitis** [TanukiSharp/MHArmory#11]
I noticed that upon upgrading from 0.8.2 to 0.8.4 some search results went missing. Here is an example, taken from 0.8.2, both overrides being off:

**Missing result:**
![mssingresult](https://user-images.githubusercontent.com/7861188/50729883-6ddd9100-114a-11e9-9dad-dce2d3d672c9.png)

This result doesn't appear in 0.8.4 anymore, and is perfectly valid. I've found that this is because Empress Coil B doesn't get elected for the search. Here is a before and after:

**0.8.2:**
![before](https://user-images.githubusercontent.com/7861188/50729911-e80e1580-114a-11e9-8640-577ba1a3e0af.png)

**0.8.4:**
![after](https://user-images.githubusercontent.com/7861188/50729917-f4926e00-114a-11e9-9267-8b3ee21d332e.png)

As you can see, there are other changes as well. I believe there is some incorrectness in the piece election algorithm. The Empress Coil gives only Tool Specialist, so I suppose because of that the election algorithm discards it, but in the end it does end up being a viable solution. I'm not entirely sure how to solve this, I'll try to give it some thought.

**Comment by TanukiSharp** [comment]
Thank you for reporting this.

As we discussed it on Discord, this is because between 0.0.8.2 and 0.0.8.4, new equipments have been introduced (some gamma armors, and the Drachen armor too) so when only the top best armor pieces are elected, now Empress ones are replaced by gamma ones.

However, there were indeed incorrectness in the equipment election, and this has been addressed in version [0.0.8.5](https://github.com/TanukiSharp/MHArmory/blob/master/ChangeLog.md#0085-20190107).

Let me know if the latest version also fixes this issue in your other sets or not.
Thanks.
