### ISSUE TITLE
Add Weapon/Weapon Info to Builds

### ISSUE THREAD

**Issue by DeveloperPaul123** [TanukiSharp/MHArmory#18]
Maybe it's beyond the scope of this project, but I really think it would be nice if "effective raw" computations were added to the sets that are built. This would necessitate adding a way to allow the user to select the weapon of their choice; but  you already have weapon data in the app itself (minus ATKT weapons?). 

[HoneyHunterWorld](https://honeyhunterworld.com/mhwb/) has done a good job IMO with including this values (EFR) and it really does allow you to min/max your builds because you can see what truly maximizes your attack values.

**Comment by TanukiSharp** [comment]
Hello @DeveloperPaul123 and thank you for your interest in Armory.

I'm afraid you are right when you say "maybe it's beyond the scope of this project", Armory is an armor set search application, not a get-me-the-max-goddamn-attack application.

I keep claiming with Armory I just want to bring an alternative and have no ambition (that would just be stupid) to replace other tools. If you want to focus on the attack, honey is the way to go for you.

Otherwise, I hope you appreciate all the goodies Armory has to offer beside that.

**Comment by DeveloperPaul123** [comment]
That's fair and also what I thought. I do enjoy using the application regardless. Thanks!

**Comment by TanukiSharp** [comment]
Thank you very much for your support :)
