### ISSUE TITLE
Suggestion: skill exclusions

### ISSUE THREAD

**Issue by duckness** [TanukiSharp/MHArmory#2]
For example, I have a melee weapon with hidden element and I want to use `Non-Elemental Boost`. This means that I don't want to see any build with `Free Elem/Ammo Up` (as it would nullify `Non-Elemental Boost`) , so it would be nice to exclude sets that have that.

**Comment by TanukiSharp** [comment]
Thank you for your suggestion.

So I think rather than trying to implement some game logic, I could simply propose a window where the user can simply specify some skills to exclude. Not that hard to do, and generic enough for all-purpose scenarios.

Do you think those skill exclusion settings should be persisted alongside the selected skills in the skill loadout ? I think so, it would make sense and so if you switch skill loadout back and forth, you don't have to keep undoing and redoing skills exclusion.

How do you think ?

**Comment by duckness** [comment]
>rather than trying to implement some game logic, I could simply propose a window where the user can simply specify some skills to exclude. Not that hard to do, and generic enough for all-purpose scenarios.

I think maybe having a `Lvl 0` option on the Skills Selector screen would be clean, but the intent and functionality might not be obvious to users.  Another way could be to add a filter option on Search Results Sorting. I like the first option more.

>Do you think those skill exclusion settings should be persisted alongside the selected skills in the skill loadout ? I think so, it would make sense and so if you switch skill loadout back and forth, you don't have to keep undoing and redoing skills exclusion.

I think so too.

**Comment by TanukiSharp** [comment]
The implementation is finished, actually it was much simpler than I expected. You can have a try by checking out the commit 9f166f442c609511291456dec1ff685acb080976.

I'm not yet sure if I will release it soon lie that or if I wait for another pending feature and ship all at once.

**Comment by TanukiSharp** [comment]
Hey, the **skill exclusion** feature has been officially shipped in version 0.0.7.3, alongside with **equipment override**, another very cool feature you may want to check.

Let me know if you find any bug or possible improvement, and thanks again for the suggestion, it's a very nice idea ;)

**Comment by duckness** [comment]
Looks good!
