### ISSUE TITLE
Lunastra Gamma

### ISSUE THREAD

**Issue by duckness** [TanukiSharp/MHArmory#3]
Lunastra's Gamma gear is currently together with the alpha and beta sets if the box is checked in the Events window. It should be separated out as the Gamma set is from AT Lunastra.

**Comment by TanukiSharp** [comment]
I will have a look, thanks for reporting.

In the meantime to fix the issue, you can activate all the events, and then in equipment override disable only the gamma pieces.

**Comment by TanukiSharp** [comment]
Indeed the Lunastra Gamma has the same event ID than Lunastra Alpha and Beta, my apologizes.

Since event data is kind of a mess, and some event become permanent and some other pop in and out, I will remove the events window in the next release, since availability or equipments can now be much tweak much more accurately and clearly through the equipment override.

**Comment by TanukiSharp** [comment]
As stated earlier, I've released the version `0.0.8` that disables the event window.

**Note** that the equipment window now has a `Import from save...` button.

Let me know if you have any other questions.
