### ISSUE TITLE
Resetting decorations/equipment override

### ISSUE THREAD

**Issue by GediminasMasaitis** [TanukiSharp/MHArmory#5]
Currently the "Activate" checkbox allows you to quickly switch between armor pieces that you have and all armor available. That would be fine, except that the tool currently lists drachen armor, while Behemoth is not available for PC yet. So to search everything except drachen, since I've imported my save, I have to go to equipment setup and click on all armors/charms sets that I don't own in order to enable them.

A simple solution would be a "Select All" / "Deselect all" button, which would reset the configuration quickly, allowing you to quickly disable one or two specific sets.

**Comment by TanukiSharp** [comment]
Yes you are right, and this is easy to do. I will add it for the next release.

For the moment, what I can advice you to do (the less painful way) to select all, is to set the `Show` drop down menu to `Some unpossessed` and click the button to toggle all pieces. It will disappear since it will not match the condition anymore. Once you cleared the list, set `Show` to `All unpossessed` and do the same. Far from being ideal, I agree, but it saves you a lot of mouse moves.

For information, you can refer to this issue, which is kind of linked since this brings UX problem: https://github.com/TanukiSharp/MHArmory/issues/4

**Comment by TanukiSharp** [comment]
Note that [version 0.0.8.1](https://github.com/TanukiSharp/MHArmory/blob/master/ChangeLog.md#0081-20181213) has this feature.
I know you already know, just for the records :)
