### ISSUE TITLE
Can't "search" while Equipment override window is opened

### ISSUE THREAD

**Issue by Fatmice** [TanukiSharp/MHArmory#9]
Per title, maybe allow search to be performed while equipment override is being tweaked?

**Comment by TanukiSharp** [comment]
Yes this bugs me too sometimes.

This is super easy to do, however I did it that way purposefully in order to avoid user to change equipment possession during a search, which could lead to inconsistent results.

Now that I write and think about it, it is possible to start a search and then open the equipment window and change the selection, which would lead to the exact same problem anyway :/

Meaning I can make the window non-modal anyway.

Will do and keep you posted. Thanks for your input, improving the usability is also very important :)

**Comment by Fatmice** [comment]
Yes, I understand the reason for not allowing a user to execute a search while the equipment override is opened as a user can change the search space while a search is already underway.  Perhaps you can simply gray out all of the UI for the equipment override once the search button is clicked and a search is being executed.  This will allow the UI to be opened without allowing a user to accidentally/incidentally/unwittingly changing the search space and causing all sort of weird and perhaps erroneous results.

**Comment by TanukiSharp** [comment]
For now I just changed the windows behavior to non-modal (non-blocking) so it should provide more comfortable experience to users.

We can see later for side effects of allowing changes while searching, this can be an improvement done at a later stage.

The change is also done for the decorations override window and can be found in the commit 7a0309b005973f1d3408a8c3f66a97309fe4222e.

It will be included in the next release.

**Comment by TanukiSharp** [comment]
Version 0.0.8.3 is release, which addresses this issue.

See the [change log here](https://github.com/TanukiSharp/MHArmory/blob/master/ChangeLog.md#0083-20181222).

**Comment by Fatmice** [comment]
Working now.
